### ISSUE TITLE
Assignment-6 completed with work-arounds

### ISSUE THREAD

**Issue by freshbeka** [freshbeka/Assignment-6#1]
Using a template I created an report pdf from an Rmarkdown file. To do this I modified the YAML, provided some specifications on the layout, and added equations to an Rmarkdown file. Then, I began to work on references. While adding references I encountered two hiccups described below. Although these issues have workarounds, I still don't know why the occurred.

1. I cannot call any `knitcitations` commands in my Rmarkdown script without first saying, "knitcitations::". For example if my Rmarkdown file said, `r citep("10.1080/00031305.2017.1375989")` I would get an error that, "Error in citep("10.1080/00031305.2017.1375989") : could not find function "citep" " I re-installed the package, ran "library(knitcitations)" in my console, and manually toggled the package off and on with my RStudio packages tab. No matter if the package was clearly loaded, the functions from that package would not be recognized. My workaround was to always put the knitcitations:: prior to the function, (i.e. `r knitcitations::citep("10.1080/00031305.2017.1375989")`) but I still don't know why this was/is. Any ideas?
2. When I used the knit button, the References section in the pdf would not be populated with any information. But if instead in my console I ran `rmarkdown::render("hw_06_template_Stiling.Rmd")` Then, the rendered pdf would have the two references appended. I did not change the Rmarkdown file at all between these two methods, but the knit button never worked at appending references.

**Comment by mdscheuerell** [comment]
Hi Beka. It looks like you forgot to include this block of code near the top of your `.Rmd` file (after the YAML):

```
## load the package
library("knitcitations")

## clean out any existing .bib files
cleanbib()

## set pandoc for formatting
options("citation_format" = "pandoc")
```

which is why you needed `knitcitations::` in your function calls. See info [here](https://fish497.github.io/website/lectures/week_07/lec_20_markdown_1.html#knitcitations_package).

**Comment by freshbeka** [comment]
OMG!! I was *repeatedly* running that bit of code in my console before hitting knit!! Thank for for this very important clarification (insert "facepalm emoji" here).

**Comment by mdscheuerell** [comment]
OK, glad you got it all sorted out.
